### ISSUE TITLE
BUG - macOS - Able to traverse the file path with "../"

### ISSUE THREAD

**Issue by Emrix** [osiris-project/quartz#12]
**Issue**
It is possible to play a sound in a completely different folder by using "../"

**Steps to Reproduce**
1. Using macOS, start Quartz
2. Enter a path to a sound outside of the sounds folder by utilizing ".." (eg: ../../../../../Applications/Quartz Audio 2.1/Data/Sounds/Accessing1)
3. Notice that the sound plays

**Expected Result**
To negate the "../" in the file path, and play the sound if it is available, otherwise say "file not found"

**Additional Info**

**Comment by JordanDeSmith** [comment]
I found a solution for this, however before I move ahead with a pull request, there are a couple options. Right now I have it set where it can take a full file path, or just the name of a file (or sub-path) in the sounds directory. It will then check if there is a .wav at the end, and if not, add it before checking for the file. This allows for something to be put in as just the name such as "ARU" or as the full file name "ARU.wav" and it will behave the same. However, this does mean if a file of a different type, or a directory is put in, it will simply say the file doesn't exist. Is this acceptable? Or does there need to be a separate error for that case?

**Comment by JordanDeSmith** [comment]
Oh, perhaps I misunderstood. I thought the intention of the issue was to allow use of sounds outside the sounds folder.
So we don't want them to play a sound outside the folder?

**Comment by Emrix** [comment]
No, we don't want them to play outside the sound folder.  Sorry, I should have been more clear.  The worry is a security issue where you could potentially access any other part of the file system, or other items through path traversal.
